defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

files:
  image_path: images
  annotation_file: images/scc.json

data:
  patch_size: 512
  batch_size: 8
  level: 0
  patches_per_slide: 10
  mean: 0.89,0.68,0.85
  std: 0.04,0.10,0.05

training:
  scanner: p1000
  seed: 42
  lr: 1e-4
